version: '3.7'

services:
  my-backend:
    # image: app1.0
    image: namhyeonjae/deskdiary-server:latest
    # platform: linux/amd64
    env_file:
      - ./.env
    ports:
      - 4000:4000
    restart: always
    networks:
      - backend
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/certificates:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    expose:
      - '80'
      - '443'
    networks:
      - backend
    depends_on:
      - my-backend
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot: # certbot 서비스 추가
    image: certbot/certbot
    container_name: certbot_service
    volumes:
      - /home/ubuntu/certificates:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - backend
    depends_on:
      - nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  backend:
    driver: bridge
